---
title: "Assigment 3-question 1"
author: "Deepak sharma"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
runtime: shiny    
---
    
    ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, rlib, eval=TRUE, include=FALSE}
library(shiny)
library(tidyverse)
library(plotly)
library(rsconnect)
library(RCurl)

rsconnect::setAccountInfo(name='deepaksharma',
                          token='2C5EEA429A1BC55340C35C50167D6DEC',
                          secret='PcokIbuKKtg85bjRNfYbhpDGTMHRyaP5p7MNkre+')

```

```{r, data, eval=TRUE, include=FALSE}
#needed to load data from github so the shiny app would work on the webpage

mortality_data <- read_csv("https://raw.githubusercontent.com/charleyferrari/CUNY_DATA608/master/lecture3/data/cleaned-cdc-mortality-1999-2010-2.csv")

```
```{r, init_vis, eval=FALSE, include=FALSE}
#Some Data visualzations I did to see what the data was like
hist(mortality_data$Deaths)
hist(mortality_data$Population)
hist(mortality_data$Year)
```

```{r, filtr, eval=TRUE, include=FALSE}
#subsetting the data
mental_data_2010 <- filter(mortality_data, Year == 2010 & ICD.Chapter == 'Mental and behavioural disorders')
mental_data_2010 <-  mental_data_2010 %>% arrange(Crude.Rate)
#head(mental_data_2010)
```

```{r, bar_plots, eval=TRUE, include=FALSE}
#tested the plot by publsihing to my plotly page
p <- plot_ly(x = mental_data_2010$Crude.Rate, y = mental_data_2010$State, type = 'bar', text = mental_data_2010$Crude.Rate, textposition = 'auto',  color = I("grey"), orientation = 'h')


```

```{r, shny_ui, eval=TRUE}
#Adapted from https://plot.ly/r/shiny-tutorial/
ui <-# Use a fluid Bootstrap layout
    fluidPage(    
        plotlyOutput("plot"),
        verbatimTextOutput("event")
    )
```

```{r shny_server, eval=TRUE}
#Adapted from https://plot.ly/r/shiny-tutorial/
server <- function(input, output) {
    
    output$plot <- renderPlotly({
        p #used the above plotly object instead of redoing here
    })
    output$event <- renderPrint({
        d <- event_data("plotly_hover")
        if (is.null(d)) "Hover on a bar to see State Data!" else d
    })
}

shinyApp(ui, server, options = list(height = 540, width = 960))
```