---
title: "TwoChoiceTest"
author: "Deepak sharma"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
runtime: shiny     
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=TRUE,include=FALSE}
#load the needed libraries
library(shiny)
library(shinythemes)
library(tidyverse)
library(plotly)
library(rsconnect)
library(RCurl)
Sys.setenv("plotly_username"='***************')
Sys.setenv("plotly_api_key"='******************')
rsconnect::setAccountInfo(name='deepaksharma',
                          token='2C5EEA429A1BC55340C35C50167D6DEC',
                          secret='PcokIbuKKtg85bjRNfYbhpDGTMHRyaP5p7MNkre+')
```

```{r, eval=TRUE,include=FALSE}
# To publish I had to access the data from the github url instead of locally

mortality_data <- read_csv("https://raw.githubusercontent.com/charleyferrari/CUNY_DATA608/master/lecture3/data/cleaned-cdc-mortality-1999-2010-2.csv")
mortality_data <- mortality_data %>% group_by(ICD.Chapter, Year) %>% mutate(National.Ave = sum(Deaths)*1e5/sum(Population))
mortality_data_wide <- mortality_data %>% spread(State,ICD.Chapter)
```

```{r, eval=TRUE,include=FALSE}
#setting up the options for the drop-down menues for the user to select data
featureList1 <- mortality_data$State
featureList2 <- mortality_data$ICD.Chapter
ui <- fluidPage(
  # Set theme
  # Some help text
  headerPanel("Mortality Rate per Year by State"),
  # Feature selection
  sidebarPanel(
    selectInput(inputId = "featureInput1", label = "Select State(s)", choices = featureList1, selected = "AL"),
    selectInput(inputId = "featureInput2", label = "Select Disease Catagory", choices = featureList2, selected = "Neoplasms")),
 mainPanel(
      plotlyOutput('trendPlot')
    )
)
```

```{r, eval=TRUE,include=TRUE}
server <- function(input, output){
#https://plot.ly/r/shinyapp-explore-diamonds/ used as a template
  # Observes the second feature input for a change
  observeEvent(input$featureInput2,{
    # Create a convenience data.frame which can be used for charting
      dataset <-mortality_data[which(mortality_data$State == input$featureInput1 & mortality_data$ICD.Chapter == input$featureInput2),]
    # Do a plotly contour plot to visualize the two featres with
    # the number of malignant cases as size
    # Note the use of 'source' argument
    output$trendPlot <- renderPlotly({
      plot_ly(dataset, x = ~Year, y = ~Crude.Rate, type = "scatter",  name = input$featureInput1, mode = "lines+markers", source = "subset") %>%
        layout(title = paste("Mortailty vs Year for ",input$featureInput1, "and ", input$featureInput2),
               xaxis = list(title = 'Year'),
               yaxis = list(title = 'Deaths per 100,000'),
               dragmode =  "select",
               plot_bgcolor = "white")%>%
        add_trace(y = ~dataset$National.Ave, name = 'National Average',mode = 'lines+markers')
    })
  })
}
shinyApp(ui, server, options = list(height = 720, width = 1080))#I tried to make the graph bigger with little success
```